"""Portfolio construction overlays (causal, research-only)."""

from mt5_swing.portfolio.smooth_select import (
    WindowStats,
    expected_monthly_from_daily_vol,
    greedy_decorrelated_pick,
    min_mean_mo_score,
    passes_smooth_constraints,
)
from mt5_swing.portfolio.overlays import (
    apply_equity_curve_target,
    apply_month_aware_scale,
    apply_runup_throttle,
    apply_vol_target,
    causal_max_concurrent_recycle,
    clock_budget_weights,
    combine_weighted,
    daily_return_corr,
    occupancy_frame,
)
from mt5_swing.portfolio.equity_tsmom import (
    CandidateScore,
    apply_daily_budget_vt,
    apply_equity_tsmom,
    apply_monthly_budget_vt,
    daily_vol_for_monthly_budget,
    holdout_clears_promote,
    score_is_windows,
    years_each_clear,
)
from mt5_swing.portfolio.pairs_residual import (
    DEFAULT_PAIRS,
    PairSpec,
    backtest_residual_equity,
    combine_sleeve_curves,
    engle_granger_adf_stat,
    hedge_ratio_ols,
    per_leg_risk,
    residual_log,
    rolling_zscore,
)

__all__ = [
    "WindowStats",
    "expected_monthly_from_daily_vol",
    "greedy_decorrelated_pick",
    "min_mean_mo_score",
    "passes_smooth_constraints",
    "apply_equity_curve_target",
    "apply_month_aware_scale",
    "apply_runup_throttle",
    "apply_vol_target",
    "causal_max_concurrent_recycle",
    "clock_budget_weights",
    "combine_weighted",
    "daily_return_corr",
    "occupancy_frame",
    "CandidateScore",
    "apply_daily_budget_vt",
    "apply_equity_tsmom",
    "apply_monthly_budget_vt",
    "daily_vol_for_monthly_budget",
    "holdout_clears_promote",
    "score_is_windows",
    "years_each_clear",
    "DEFAULT_PAIRS",
    "PairSpec",
    "backtest_residual_equity",
    "combine_sleeve_curves",
    "engle_granger_adf_stat",
    "hedge_ratio_ols",
    "per_leg_risk",
    "residual_log",
    "rolling_zscore",
]
